const otherProducts = [
  {
    id: 81,
    name: 'Samsung Galaxy',
    imageUrl: '/Product_img/watch-01.png',
    price: 199,
    rating: 4.5,
    brand: 'Samsung',
    type: 'Watches',
    material: 'Metal',
    color: 'Black',
    weight: 'Light',
    stock: 10,
    shortDescription: 'A stylish and sleek metal-bodied smartwatch by Samsung, perfect for fitness tracking and notifications.',
    detailDescription: 'The Samsung Galaxy Watch 4 combines premium design with functionality, offering health monitoring, fitness tracking, and seamless notifications. With its durable metal body and vibrant display, it’s perfect for both casual and active lifestyles.'
  },
  {
    id: 82,
    name: 'Fossil Hybrid HR',
    imageUrl: '/Product_img/watch-02.jpg',
    price: 249,
    rating: 4.2,
    brand: 'Fossil',
    type: 'Watches',
    material: 'Leather',
    color: 'Silver',
    weight: 'Medium',
    stock: 5,
    shortDescription: 'A classic hybrid watch by Fossil, combining vintage looks with modern technology.',
    detailDescription: 'The Fossil Hybrid HR blends traditional aesthetics with modern smartwatch features. It includes long battery life, and all while maintaining the elegance of a belt-strap watch.'
  },
  {
    id: 83,
    name: 'Garmin Fenix 6X',
    imageUrl: '/Product_img/watch-03.jpg',
    price: 299,
    rating: 4.7,
    brand: 'Garmin',
    type: 'Watches',
    material: 'Metal',
    color: 'Silver',
    weight: 'Light',
    stock: 8,
    shortDescription: 'A high-performance multisport watch from Garmin',
    detailDescription: 'Garmin Fenix is designed for athletes and adventurers, and multiple sport modes. Its rugged metal body and versatile functionality make it ideal for outdoor enthusiasts.'
  },
  {
    id: 84,
    name: 'Tag Heuer Connected',
    imageUrl: '/Product_img/watch-04.jpg',
    price: 399,
    rating: 4.9,
    brand: 'Tag Heuer',
    type: 'Watches',
    material: 'Leather',
    color: 'Black',
    weight: 'Medium',
    stock: 7,
    shortDescription: 'A luxury smartwatch from Tag Heuer, blending premium design with cutting-edge technology.',
    detailDescription: 'The Tag Heuer Connected offers the perfect blend of luxury and technology. With a premium leather strap and advanced fitness tracking, it is designed for individuals who appreciate elegance and performance.'
  },
  {
    id: 91,
    name: 'Xiaomi Redmi Note 13',
    imageUrl: '/Product_img/phone1.jpg',
    price: 799,
    rating: 4.8,
    brand: 'Xiaomi',
    type: 'Mobiles',
    material: 'Metal',
    color: 'White',
    weight: 'Heavy',
    stock: 15,
    shortDescription: 'A powerful Xiaomi smartphone designed for mobile gaming and high performance.',
    detailDescription: 'The Xiaomi Redmi Note 13 features a sleek metal design and a high-refresh-rate display, making it ideal for gaming and multitasking. Its powerful chipset ensures smooth performance, while its long-lasting battery is perfect for heavy users.'
  },
  {
    id: 92,
    name: 'Samsung Galaxy F23',
    imageUrl: '/Product_img/phone2.jpg',
    price: 899,
    rating: 4.5,
    brand: 'Samsung',
    type: 'Mobiles',
    material: 'Plastic',
    color: 'Silver',
    weight: 'Medium',
    stock: 7,
    shortDescription: 'An affordable Samsung smartphone offering fast performance and a great camera.',
    detailDescription: 'The Samsung Galaxy F23 provides excellent performance with its efficient chipset and long-lasting battery. With a sturdy plastic body and an impressive camera, it’s a great choice for users who want value without compromising on features.'
  },
  {
    id: 93,
    name: 'Realme 8 Pro',
    imageUrl: '/Product_img/phone3.jpg',
    price: 999,
    rating: 4.9,
    brand: 'Oppo',
    type: 'Mobiles',
    material: 'Plastic',
    color: 'Gray',
    weight: 'Medium',
    stock: 12,
    shortDescription: 'A sleek Realme smartphone offering cutting-edge technology with a striking blue finish.',
    detailDescription: 'The Realme 8 Pro combines fast performance with a stunning design. Its blue plastic body is both durable and lightweight, and its advanced camera system makes it perfect for photography enthusiasts.'
  },
  {
    id: 94,
    name: 'Motorola Edge 40 Neo',
    imageUrl: '/Product_img/phone4.jpg',
    price: 1099,
    rating: 4.6,
    brand: 'Motorola',
    type: 'Mobiles',
    material: 'Glass',
    color: 'Silver',
    weight: 'Heavy',
    stock: 10,
    shortDescription: 'A premium Motorola smartphone with a glass back, offering a great camera and battery life.',
    detailDescription: 'The Motorola Edge 40 Neo is designed for those who prioritize aesthetics and performance. With a premium glass body and a powerful camera system, it’s ideal for users who want a high-end smartphone experience.'
  },
  {
    id: 95,
    name: 'iPhone 13',
    imageUrl: '/Product_img/phone5.jpg',
    price: 1599,
    rating: 4.8,
    brand: 'Apple',
    type: 'Mobiles',
    material: 'Glass',
    color: 'Silver',
    weight: 'Heavy',
    stock: 10,
    shortDescription: 'The latest iPhone with cutting-edge technology and a sleek glass body.',
    detailDescription: 'The iPhone 13 offers unparalleled performance with its A15 Bionic chip, stunning display, and excellent camera system. Its glass back adds a premium feel, making it a top choice for iPhone fans.'
  },
  {
    id: 71,
    name: 'Dell Inspiron 15',
    imageUrl: '/Product_img/laptop1.jpg',
    price: 1199,
    rating: 4.7,
    brand: 'Dell',
    type: 'Laptops',
    material: 'Aluminum',
    color: 'Gray',
    weight: 'Heavy',
    stock: 8,
    shortDescription: 'A high-performance Dell laptop designed for both professionals and students.',
    detailDescription: 'The Dell Inspiron 15 combines powerful performance with a sleek aluminum design. Its large display and excellent battery life make it perfect for professionals and students alike.'
  },
  {
    id: 72,
    name: 'HP 15s',
    imageUrl: '/Product_img/laptop2.jpg',
    price: 1299,
    rating: 4.6,
    brand: 'HP',
    type: 'Laptops',
    material: 'Plastic',
    color: 'Gray',
    weight: 'Heavy',
    stock: 10,
    shortDescription: 'An affordable HP laptop offering good performance and a long battery life.',
    detailDescription: 'The HP 15s is designed for users who need a reliable laptop for everyday tasks. Its plastic body is durable, and its battery life is excellent, making it a solid choice for students and home users.'
  },
  {
    id: 73,
    name: 'Lenovo IdeaPad 5',
    imageUrl: '/Product_img/laptop3.jpg',
    price: 1399,
    rating: 4.8,
    brand: 'Lenovo',
    type: 'Laptops',
    material: 'Aluminum',
    color: 'Silver',
    weight: 'Medium',
    stock: 6,
    shortDescription: 'A lightweight Lenovo laptop with a sleek aluminum design and good performance.',
    detailDescription: 'The Lenovo IdeaPad 5 is perfect for both work and play, featuring a lightweight aluminum body and powerful specs. Its vibrant display and excellent battery life make it a great choice for anyone looking for a portable laptop.'
  },
  {
    id: 74,
    name: 'Lenovo Think Pad',
    imageUrl: '/Product_img/laptop4.jpg',
    price: 1499,
    rating: 4.8,
    brand: 'Lenovo',
    type: 'Laptops',
    material: 'Aluminum',
    color: 'Black',
    weight: 'Medium',
    stock: 6,
    shortDescription: 'A lightweight Lenovo laptop with a sleek aluminum design and good performance.',
    detailDescription: 'The Lenovo Think Pad is perfect for both work and play, featuring a lightweight aluminum body and powerful specs. Its vibrant display and excellent battery life make it a great choice for anyone looking for a portable laptop.'
  },
  {
    id: 75,
    name: 'HP Pavillion',
    imageUrl: '/Product_img/laptop5.jpg',
    price: 1699,
    rating: 4.7,
    brand: 'Hp',
    type: 'Laptops',
    material: 'Plastic',
    color: 'Silver',
    weight: 'Medium',
    stock: 4,
    shortDescription: 'Hp Pavallion laptop offering cutting-edge technology, lightweight design, and fast performance for multitaskers.',
    detailDescription: 'Hp Pavallion offers the latest technology in a sleek and lightweight body. Its fast processing power is ideal for multitasking, while its plastic construction ensures durability without adding extra weight. A great option for both professionals and students.'
  }
];


export default otherProducts;
