const otherProducts = [
    { 
      id: 81, 
      name: 'Royal Smart Watch', 
      imageUrl: '/Product_img/watch-01.png', 
      price: 199, 
      rating: 4.5, 
      brand: 'Samsung', 
      type: 'Watches', 
      material: 'Metal', 
      color: 'Black', 
      weight: 'Light', 
      stock: 10, 
      shortDescription: 'A stylish and sleek metal-bodied smartwatch by Samsung, perfect for fitness tracking and notifications.',
      detailDescription: 'The Royal Smart Watch from Samsung is a premium accessory designed for both style and functionality. With a metal body, it offers durability and elegance. Featuring advanced fitness tracking, heart rate monitoring, and seamless notifications, it is the perfect companion for your busy lifestyle.'
    },
    { 
      id: 82, 
      name: 'Digital Watch', 
      imageUrl: '/Product_img/watch-02.jpg', 
      price: 249, 
      rating: 4.0, 
      brand: 'Fossil', 
      type: 'Watches', 
      material: 'Leather', 
      color: 'Brown', 
      weight: 'Medium', 
      stock: 5, 
      shortDescription: 'Classic leather digital watch by Fossil, combining vintage looks with modern technology.',
      detailDescription: 'This Fossil Digital Watch offers a blend of traditional leather craftsmanship and cutting-edge digital features. It provides a comfortable fit with a brown leather strap, while its digital display makes it easy to keep track of time, fitness stats, and notifications.'
    },
    { 
      id: 83, 
      name: 'Silvery Watch', 
      imageUrl: '/Product_img/watch-03.jpg', 
      price: 299, 
      rating: 4.7, 
      brand: 'Garmin', 
      type: 'Watches', 
      material: 'Metal', 
      color: 'Silver', 
      weight: 'Light', 
      stock: 8, 
      shortDescription: 'High-performance silver watch from Garmin, featuring multi-sport modes and advanced health tracking.',
      detailDescription: 'Garmin’s Silvery Watch is an elegant yet highly functional smartwatch, designed for athletes and fitness enthusiasts. Its silver body adds a sophisticated touch, while built-in GPS, heart rate monitoring, and advanced multi-sport modes cater to all your fitness tracking needs.'
    },
    { 
      id: 84, 
      name: 'Matte Black Watch', 
      imageUrl: '/Product_img/watch-04.jpg', 
      price: 349, 
      rating: 5.0, 
      brand: 'Tag Heuer', 
      type: 'Watches', 
      material: 'Leather', 
      color: 'Brown', 
      weight: 'Medium', 
      stock: 7, 
      shortDescription: 'Premium matte black leather watch from Tag Heuer, blending luxury and performance.',
      detailDescription: 'The Matte Black Watch from Tag Heuer combines high-end luxury with exceptional functionality. Its leather strap provides a comfortable fit, while the high-performance materials ensure durability. Ideal for formal settings or an active lifestyle, it balances aesthetics with advanced features like fitness tracking.'
    },
    { 
      id: 91, 
      name: 'Xiaomi Pro', 
      imageUrl: '/Product_img/phone1.jpg', 
      price: 799, 
      rating: 4.8, 
      brand: 'Xiaomi', 
      type: 'Mobiles', 
      material: 'Metal', 
      color: 'Gray', 
      weight: 'Heavy', 
      stock: 15, 
      shortDescription: 'Powerful Xiaomi smartphone featuring a sleek metal design, perfect for high-performance mobile gaming and multitasking.',
      detailDescription: 'The Xiaomi Pro offers exceptional performance with its metal body, ensuring durability and heat management. Designed for gamers and multitaskers, it features a high refresh rate display, powerful chipset, and long-lasting battery life. A top-tier smartphone for those who demand more from their devices.'
    },
    { 
      id: 92, 
      name: 'One Plus', 
      imageUrl: '/Product_img/phone2.png', 
      price: 899, 
      rating: 4.5, 
      brand: 'OnePlus', 
      type: 'Mobiles', 
      material: 'Plastic', 
      color: 'Black', 
      weight: 'Medium', 
      stock: 7, 
      shortDescription: 'OnePlus smartphone offering fast performance, excellent camera, and a premium feel.',
      detailDescription: 'The OnePlus delivers a premium experience with its high-performance chipset and fast charging capabilities. With a plastic yet sturdy body, it offers great durability while keeping the phone lightweight. Its camera system excels in low light, making it ideal for photography enthusiasts.'
    },
    { 
      id: 93, 
      name: 'Oppo K10', 
      imageUrl: '/Product_img/phone3.png', 
      price: 999, 
      rating: 4.9, 
      brand: 'Oppo', 
      type: 'Mobiles', 
      material: 'Plastic', 
      color: 'Blue', 
      weight: 'Medium', 
      stock: 12, 
      shortDescription: 'Oppo K10 offers cutting-edge mobile technology with a striking blue finish and long battery life.',
      detailDescription: 'Oppo K10 is designed for users who need fast performance and long battery life. The plastic body ensures durability without adding extra weight. This phone also features a stunning blue finish and comes equipped with fast charging, a high-refresh-rate display, and a camera perfect for all lighting conditions.'
    },
    { 
      id: 94, 
      name: 'Oppo A51', 
      imageUrl: '/Product_img/phone4.png', 
      price: 1099, 
      rating: 4.6, 
      brand: 'Oppo', 
      type: 'Mobiles', 
      material: 'Glass', 
      color: 'White', 
      weight: 'Heavy', 
      stock: 10, 
      shortDescription: 'Oppo A51 smartphone with a glass back, offering a premium feel and a high-quality camera for photography lovers.',
      detailDescription: 'The Oppo A51 combines elegance with performance, featuring a glass back that adds a premium touch. With advanced camera features and long-lasting battery, this smartphone is a great option for those who prioritize both aesthetics and functionality.'
    },
    { 
      id: 71, 
      name: 'Pro Art Lenovo', 
      imageUrl: '/Product_img/laptop1.jpg', 
      price: 1199, 
      rating: 4.7, 
      brand: 'Lenovo', 
      type: 'Laptops', 
      material: 'Aluminum', 
      color: 'Silver', 
      weight: 'Heavy', 
      stock: 8, 
      shortDescription: 'Lenovo Pro Art laptop designed for professionals, with a sleek aluminum body and powerful performance.',
      detailDescription: 'Lenovo Pro Art is crafted for professionals who need top-tier performance. Its aluminum body provides durability and a premium feel, while the high-performance specs cater to creators and designers looking for excellent processing power, a vibrant display, and long battery life.'
    },
    { 
      id: 72, 
      name: 'Apple Mac Book', 
      imageUrl: '/Product_img/laptop2.jpg', 
      price: 1299, 
      rating: 4.6, 
      brand: 'Apple', 
      type: 'Laptops', 
      material: 'Plastic', 
      color: 'Black', 
      weight: 'Heavy', 
      stock: 10, 
      shortDescription: 'Apple MacBook with cutting-edge M1 chip, offering performance for creative professionals and long battery life.',
      detailDescription: 'Apple’s MacBook is known for its seamless performance and cutting-edge technology. Powered by the M1 chip, it offers incredible processing power, excellent battery life, and a stunning display. Ideal for creative professionals and anyone needing a reliable machine for heavy tasks.'
    },
    { 
      id: 73, 
      name: 'HP Pro', 
      imageUrl: '/Product_img/laptop3.jpg', 
      price: 1399, 
      rating: 4.8, 
      brand: 'HP', 
      type: 'Laptops', 
      material: 'Aluminum', 
      color: 'Gray', 
      weight: 'Medium', 
      stock: 6, 
      shortDescription: 'HP Pro laptop offering high performance, lightweight design, and a great display for work or entertainment.',
      detailDescription: 'The HP Pro combines sleek design with powerful performance, making it perfect for work and entertainment. Its aluminum body provides durability, while its vibrant display and strong battery life make it a great choice for professionals on the go.'
    },
    { 
      id: 74, 
      name: '12th Gen i5', 
      imageUrl: '/Product_img/laptop4.jpeg', 
      price: 1499, 
      rating: 4.9, 
      brand: 'Dell', 
      type: 'Laptops', 
      material: 'Plastic', 
      color: 'White', 
      weight: 'Medium', 
      stock: 4, 
      shortDescription: 'Dell 12th Gen i5 laptop offering cutting-edge technology, lightweight design, and fast performance for multitaskers.',
      detailDescription: 'Dell’s 12th Gen i5 laptop offers the latest technology in a sleek and lightweight body. Its fast processing power is ideal for multitasking, while its plastic construction ensures durability without adding extra weight. A great option for both professionals and students.'
    }
  ];
  

export default otherProducts;
