const products = [
  {
      id: 1,
      name: "Product 1",
      imageUrl: "/Product_img/products1.png", // Ensure correct image path
      rating: 4.5,
      price: 29.99,
      reviews: 245,
  },
  {
      id: 2,
      name: "Product 2",
      imageUrl: "/Product_img/products2.png",
      rating: 4.2,
      price: 39.99,
      reviews: 130,
  },
  {
      id: 3,
      name: "Product 3",
      imageUrl: "/Product_img/products3.png",
      rating: 5.0,
      price: 49.99,
      reviews: 310,
  },
  {
      id: 4,
      name: "Product 4",
      imageUrl: "/Product_img/products4.png",
      rating: 5.0,
      price: 49.99,
      reviews: 310,
  },
  {
      id: 5,
      name: "Product 5",
      imageUrl: "/Product_img/products5.png",
      rating: 4.0,
      price: 19.99,
      reviews: 120,
  },
  {
      id: 6,
      name: "Product 6",
      imageUrl: "/Product_img/products6.png",
      rating: 4.8,
      price: 69.99,
      reviews: 500,
  },
  {
      id: 7,
      name: "Product 7",
      imageUrl: "/Product_img/products7.png",
      rating: 3.9,
      price: 22.99,
      reviews: 85,
  },
  {
      id: 8,
      name: "Product 8",
      imageUrl: "/Product_img/products8.png",
      rating: 4.3,
      price: 33.99,
      reviews: 205,
  },
  {
      id: 9,
      name: "Product 9",
      imageUrl: "/Product_img/products9.png",
      rating: 4.7,
      price: 55.99,
      reviews: 315,
  },
  {
      id: 10,
      name: "Product 10",
      imageUrl: "/Product_img/products10.png",
      rating: 5.0,
      price: 89.99,
      reviews: 400,
  },
  {
      id: 11,
      name: "Product 11",
      imageUrl: "/Product_img/products11.png",
      rating: 4.1,
      price: 23.99,
      reviews: 160,
  },
  {
      id: 12,
      name: "Product 12",
      imageUrl: "/Product_img/products12.png",
      rating: 4.6,
      price: 42.99,
      reviews: 280,
  },
];

export default products;